from source.NetworkTestCases import NetworkTestCases

tests = NetworkTestCases()
print()
print()
print("testing success with the same policy")
print()
tests.test_success_same_policy()
print("-----------------------------------------------------------")
print()
print("testing success with policy sync")
print()
tests.test_success_policy_sync()
print("-----------------------------------------------------------")
print()
print("testing unauthorized host attempting to communicate")
print()
tests.test_failure_host_key_not_authorized()
print("-----------------------------------------------------------")
print()
print("testing invalid policy criteria")
print()
tests.test_failure_unauthorized_policy_criteria()
print("-----------------------------------------------------------")